<a href="https://colab.research.google.com/github/Debasmita0596/Python-Basics-Assignment/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

NumPy (Numerical Python) is a powerful library in Python that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. It is fundamental for scientific computing and data analysis in Python because it enhances performance, ease of use, and functionality for numerical operations.

Purpose of NumPy in Scientific Computing and Data Analysis
Efficient Data Structures: NumPy provides the ndarray, a fast, space-efficient multi-dimensional array that allows users to store large datasets in memory and perform operations on them efficiently. Arrays are central to many scientific computing tasks, such as matrix manipulations, statistics, linear algebra, and Fourier transforms.

Vectorization of Operations: NumPy allows for vectorized operations, where operations that would traditionally require looping in Python (e.g., adding two lists element-wise) can be written in a concise and readable form. This reduces the overhead of loops, which are generally slow in Python, and leverages highly optimized C or Fortran code running in the background.

Mathematical Functions: NumPy provides a comprehensive collection of mathematical functions that can be applied to arrays element-wise. This includes trigonometric functions, logarithms, linear algebra routines, and random number generation, all optimized for performance.

Interoperability with Other Libraries: NumPy is the foundation of many other scientific libraries like SciPy, pandas, and scikit-learn. These libraries depend on NumPy arrays for data representation, making it a cornerstone of the Python scientific computing ecosystem.

Handling Missing Data: While other libraries like pandas are more focused on data manipulation, NumPy can be used for scientific computing tasks where missing data needs to be represented efficiently, such as using masked arrays.

Broadcasting: NumPy arrays support broadcasting, which allows arithmetic operations on arrays of different shapes. This eliminates the need to manually reshape or replicate arrays, improving code simplicity and efficiency.

Advantages of Using NumPy
Performance and Speed: NumPy's operations are implemented in C, which makes them faster than native Python functions. The efficient memory layout and ability to perform operations in a vectorized form result in substantial performance gains, especially for large datasets.

Memory Efficiency: NumPy arrays consume less memory compared to equivalent Python lists. This is because NumPy arrays are homogeneous (i.e., all elements in the array are of the same type), whereas Python lists are heterogeneous and have more overhead.

Concise and Readable Code: By using array operations (e.g., array1 + array2), NumPy allows developers to avoid writing explicit loops, making the code more concise, easier to read, and often faster due to reduced Python overhead.

Advanced Mathematical Functions: NumPy provides support for advanced mathematical operations such as Fourier transforms, matrix decompositions, and random number generation, all optimized for performance.

Cross-platform and Multidimensional Support: NumPy arrays work across platforms and support up to N dimensions. This makes it an ideal tool for working with complex datasets that involve multiple dimensions (e.g., images, videos, or higher-dimensional scientific data).

Integration with Other Tools: NumPy integrates well with libraries like matplotlib (for plotting), pandas (for data manipulation), and scikit-learn (for machine learning), making it highly versatile.

How NumPy Enhances Python’s Numerical Capabilities
Array-based Operations: NumPy enhances Python’s capabilities by providing an array object (ndarray) that is much more efficient than Python’s native lists. Array-based operations like addition, multiplication, and more can be performed in a vectorized manner, which speeds up computation and simplifies code.

Mathematical Operations: While Python’s standard library includes basic numerical operations, NumPy extends these with functions for linear algebra, random number generation, and various mathematical operations (e.g., sin, cos, exp, etc.), all optimized for speed.

Data Handling for Machine Learning: NumPy arrays are the standard for handling datasets in machine learning. Libraries like TensorFlow, PyTorch, and scikit-learn rely heavily on NumPy arrays for input data, training models, and performing matrix operations.

Parallelism and Efficiency: NumPy uses optimized C and Fortran routines internally, allowing for parallel execution of operations like matrix multiplications, which would be slower if implemented purely in Python.

In summary, NumPy enhances Python's scientific computing capabilities by providing efficient, fast, and easy-to-use array-based data structures and functions that make numerical operations and data analysis both faster and more concise. Its support for vectorized operations, broadcasting, and a wide range of mathematical functions allows for efficient and scalable scientific computing in Python.



In [6]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

#In NumPy, both np.mean() and np.average() are used to compute the central tendency (or the average) of an array of numbers.
#However, they have distinct differences in their behavior and use cases, especially when weights are involved.


#1. np.mean()

#Purpose: np.mean() calculates the arithmetic mean (simple average) of the elements in an array, which is the sum of all elements divided by the number of elements.
#Syntax: np.mean(a, axis=None, dtype=None, out=None, keepdims=False)

#Key Characteristics:
#It computes the mean of the array elements along the specified axis (or across the entire array if no axis is specified).
#It does not support weights. Every element in the array is treated equally.
#It is generally used when all elements have the same importance.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)  # Output: 3.0

#2. np.average()

#Purpose: np.average() computes a weighted average of the elements in an array.
#It gives you the flexibility to assign different weights to elements based on their relative importance.

#Syntax: np.average(a, axis=None, weights=None, returned=False)

#Key Characteristics:

#It can compute both the simple mean (if weights=None) and the weighted mean (if weights is specified).
#If the weights parameter is specified, the function computes the weighted average, where each element is multiplied by its corresponding weight, and then the sum is divided by the total weight.
#If the returned=True parameter is used, it also returns the sum of weights along with the average.
#Typically used when some data points are more important than others, and thus require different weights.

#Example (Simple Average):
arr = np.array([1, 2, 3, 4, 5])
avg_value = np.average(arr)  # Output: 3.0 (same as np.mean() since no weights are provided)

#Example (Weighted Average):
weights = np.array([1, 2, 3, 4, 5])  # The importance or weight of each element
weighted_avg = np.average(arr, weights=weights)  # Output: 3.6667

#Differences Between np.mean() and np.average()

 #Feature                                 	np.mean()	                                                                           np.average()

#Weight Support	               Does not support weights (simple mean only). 	                                       Supports weights (can compute weighted mean).


#Returned Value                        	Only returns the mean.	                                                     Can return the sum of weights if returned=True.


#Use Case              	When you need to compute a simple average where all elements are treated equally.     	    When some elements have different importance (weights) or you need a weighted average.


#Syntax Simplicity	                 Simple, as it only computes the arithmetic mean.	                        Slightly more flexible with options for weights and returning the sum of weights.



#When to Use np.mean() vs np.average()

#Use np.mean() when:

# Want to calculate the simple arithmetic mean of an array without considering weights.
# All elements in the array have equal significance.

#Use np.average() when:

#Need to compute a weighted average, meaning some elements have more significance (importance) than others.
#Need both the average and the sum of weights (by using the returned=True parameter).
#For cases where weights are involved, like in data where certain observations or measurements carry more weight or relevance (e.g., calculating the average score of students where each subject has different credit points).

#Summary
#np.mean(): Use it for straightforward averaging, treating all values equally.
#np.average(): Use it when you need a weighted average or more control over the calculation of the average, especially if some values have more significance than others



In [ ]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D array.

#Reversing a NumPy array can be done in various ways depending on the number of dimensions (1D, 2D, etc.) and the axis along which you want to reverse the elements. Below are the common methods for reversing arrays in NumPy:

#Methods for Reversing a NumPy Array
#1.Using Slicing ([::-1])

#Slicing is the most straightforward and Pythonic way to reverse a NumPy array. The [::-1] syntax means "reverse the array by taking elements from the end to the beginning."

#2.Using np.flip()

#np.flip() is a NumPy function that reverses the order of elements along the specified axis or axes. It can handle multi-dimensional arrays and reverse along any axis.

#3.Using np.fliplr() and np.flipud() (2D Arrays)
#np.fliplr() flips the array from left to right (along columns).
#np.flipud() flips the array upside down (along rows).


#1. Reversing a 1D Array

#Method 1: Using Slicing ([::-1])
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reversing using slicing
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)  # Output: [5 4 3 2 1]

#Method 2: Using np.flip()
# Reversing using np.flip()
reversed_arr_1d_flip = np.flip(arr_1d)
print(reversed_arr_1d_flip)  # Output: [5 4 3 2 1]

#2. Reversing a 2D Array
#Let's take a 2D array and explore different ways to reverse it along various axes.

#Method 1: Using Slicing ([::-1])
#Reversing Along Rows (Axis 0): To reverse along rows (flip rows upside down), you can use [::-1] on the first axis.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reversing along rows (axis 0)
reversed_arr_2d_rows = arr_2d[::-1, :]
print(reversed_arr_2d_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

#Reversing Along Columns (Axis 1): To reverse along columns (flip left to right), you can use [::-1] on the second axis.

# Reversing along columns (axis 1)
reversed_arr_2d_cols = arr_2d[:, ::-1]
print(reversed_arr_2d_cols)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

#Method 2: Using np.flip()
#Reversing Along Rows (Axis 0):
reversed_arr_2d_flip_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_2d_flip_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

#Reversing Along Columns (Axis 1):
reversed_arr_2d_flip_cols = np.flip(arr_2d, axis=1)
print(reversed_arr_2d_flip_cols)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

#Reversing Along Both Axes:
reversed_arr_2d_flip_both = np.flip(arr_2d)
print(reversed_arr_2d_flip_both)
# Output:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]

#Method 3: Using np.fliplr() and np.flipud()
#Using np.fliplr() to Reverse Left to Right (Columns):

reversed_arr_2d_lr = np.fliplr(arr_2d)
print(reversed_arr_2d_lr)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

#Using np.flipud() to Reverse Upside Down (Rows):
reversed_arr_2d_ud = np.flipud(arr_2d)
print(reversed_arr_2d_ud)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

#Summary
#For 1D arrays, the simplest way to reverse is using slicing ([::-1]) or np.flip().
#For 2D arrays, you can reverse along different axes:
#Use slicing ([::-1]) or np.flip() to reverse along any axis (rows, columns, or both).
#Use np.fliplr() for reversing columns (left to right) and np.flipud() for reversing rows (upside down).


In [ ]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
'''Determining the Data Type of Elements in a NumPy Array
To determine the data type of elements in a NumPy array, you can use the dtype attribute of the array.'''
#Here's an example:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4])

# Determine the data type of the elements
print(arr.dtype)
#Output:int64
#In this example, arr.dtype shows that the elements in the array are of type int64 (64-bit integers).
#Importance of Data Types in Memory Management and Performance
'''1. Memory Management
Data types in NumPy are critical for efficient memory usage because NumPy arrays are stored as contiguous blocks of memory, unlike Python lists which are pointers to objects. Choosing the appropriate data type for an array can greatly reduce memory consumption, especially when working with large datasets.
Memory Efficiency: Each data type (such as int8, int32, float64, etc.) consumes a fixed amount of memory. For example, int8 uses 1 byte per element, while float64 uses 8 bytes per element. If you are only working with small numbers, using a larger data type like int64 or float64 would waste memory. In contrast, using a smaller type like int8 or float32 would save memory.'''
'''Example:

A NumPy array of 1 million integers:
int8 (1 byte per element) would use 1MB of memory.
int64 (8 bytes per element) would use 8MB of memory.'''
#Thus, choosing an appropriate data type can lead to significant memory savings.
'''2. Performance Optimization
Data types in NumPy directly affect the performance of operations due to the way data is stored and processed:

Faster Computations: NumPy arrays are designed to perform element-wise operations much faster than Python lists because they use low-level, highly optimized C-based routines. Operations are vectorized, meaning they are applied across the array in a single step. When the data type is smaller (e.g., int16 instead of int64), NumPy can process more elements in a single operation, leading to faster computations.

Cache Efficiency: Smaller data types can fit more data into the CPU cache, reducing the number of memory accesses required and improving performance, especially when processing large datasets.

Precision: In some cases, using a higher precision data type (e.g., float64 instead of float32) is necessary for accurate calculations, but it comes at the cost of performance and memory. Choosing a data type that balances precision and performance is important for certain applications, such as scientific computing or machine learning.'''
#Example: Impact of Data Type on Performance
import numpy as np
import time

# Create large arrays of different data types
arr_int32 = np.random.randint(0, 100, size=1000000, dtype='int32')
arr_int64 = np.random.randint(0, 100, size=1000000, dtype='int64')

# Measure time for summing the arrays
start = time.time()
np.sum(arr_int32)
print("Time for int32:", time.time() - start)

start = time.time()
np.sum(arr_int64)
print("Time for int64:", time.time() - start)
'''In this example, you might observe a difference in the time it takes to perform the summation depending on the data type. The performance difference becomes noticeable when dealing with large arrays.

Summary of Importance
Memory Efficiency: Smaller data types save memory, which is crucial for large datasets.
Performance: Smaller or appropriate data types can lead to faster operations because they take up less space and can be processed more efficiently by the CPU.
Precision: Choosing the right data type ensures the accuracy of computations while balancing memory and speed.
Selecting the correct data type in NumPy is essential for optimizing both memory usage and computational performance, especially in large-scale data analysis and scientific computing.'''


In [ ]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
'''ndarray in NumPy
An ndarray (short for "N-dimensional array") is the core data structure in NumPy, designed for efficient storage and manipulation of large datasets. It is a multidimensional, homogeneous array that can store elements of the same data type (e.g., integers, floats, etc.) in a contiguous block of memory.'''
'''Key Features of ndarrays
N-dimensional:

ndarrays can be one-dimensional (1D), two-dimensional (2D), or multi-dimensional (N-dimensional), allowing for complex data representation.
Homogeneous Data Types:

All elements in an ndarray are of the same data type, which allows for efficient memory usage and performance. You can specify the data type using the dtype parameter when creating an array.
Contiguous Memory Allocation:

The elements of an ndarray are stored in contiguous memory locations, which leads to improved performance for mathematical operations and data processing.
Vectorized Operations:

NumPy supports element-wise operations (like addition, subtraction, multiplication, etc.) that are applied directly to the arrays without the need for explicit loops. This allows for concise and efficient code.
Broadcasting:

NumPy can automatically expand arrays of different shapes during arithmetic operations, allowing for flexibility in array operations.
Flexible Indexing:

ndarrays support advanced indexing and slicing, enabling easy access to specific elements, rows, columns, or subarrays.
Rich Functionality:

NumPy provides a wide range of built-in functions and methods for array manipulation, mathematical operations, statistical analysis, linear algebra, and more.'''

#Differences from Standard Python Lists

#Feature	                                               NumPy ndarray	                                                                                   Python List

#Data Type	                          Homogeneous (all elements are of the same type)	                                                             Heterogeneous (elements can be of different types)

#Performance	                      More efficient for large datasets due to contiguous memory allocation and vectorized operations	              Slower for numerical computations due to dynamic typing and overhead of storing pointers

#Memory Usage	                     More memory-efficient due to fixed size and type	                                                            Less efficient, as it stores references to objects

#N-dimensional Support	         Supports multi-dimensional arrays natively	                                                               Limited to 1D (can create lists of lists for 2D, but not as efficient)

#Element-wise Operations      	Supports vectorized operations directly	                                                               Requires explicit loops for element-wise operations

#Slicing and Indexing	             Advanced slicing and indexing capabilities (e.g., fancy indexing)	                                 Basic indexing and slicing, but less flexible

#Functionality	                  Extensive mathematical and statistical functions                                               	Limited built-in functions for numerical computations


#Example of ndarrays vs. Python Lists

#Creating a NumPy Array

import numpy as np

# Create a NumPy array
ndarray = np.array([1, 2, 3, 4, 5])
print("NumPy Array:", ndarray)

#Creating a Python List
# Create a Python list
py_list = [1, 2, 3, 4, 5]
print("Python List:", py_list)

#Element-wise Operation with NumPy
# Element-wise addition with NumPy
result_ndarray = ndarray + 10
print("NumPy Array After Addition:", result_ndarray)

#Element-wise Operation with Python List

# Element-wise addition with Python list (requires a loop)
result_py_list = [x + 10 for x in py_list]
print("Python List After Addition:", result_py_list)

#Output:
'''NumPy Array: [1 2 3 4 5]
Python List: [1, 2, 3, 4, 5]
NumPy Array After Addition: [11 12 13 14 15]
Python List After Addition: [11, 12, 13, 14, 15]'''

'''Summary
ndarrays are powerful and efficient for numerical computations and data analysis in Python. They provide significant advantages over standard Python lists in terms of performance, memory efficiency, and functionality, particularly for large datasets and complex operations. Their design is optimized for mathematical and scientific computations, making them a fundamental component of the NumPy library and widely used in data science and machine learning applications.'''


In [ ]:
#6.Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
'''NumPy arrays offer significant performance benefits over Python lists, especially for large-scale numerical operations. Here’s a detailed analysis of these benefits:

1. Memory Efficiency
Contiguous Memory Allocation: NumPy arrays are stored in contiguous blocks of memory, which means they require less overhead than Python lists. Python lists are essentially arrays of pointers to objects, leading to higher memory consumption.
Fixed Data Types: NumPy arrays are homogeneous, meaning all elements are of the same data type. This allows for optimized memory allocation and reduces the overhead of storing type information for each element. In contrast, Python lists can hold mixed data types, leading to inefficient memory use.
2. Speed of Operations
Vectorized Operations: NumPy enables vectorized operations, allowing arithmetic operations to be performed on entire arrays without explicit loops. This takes advantage of low-level optimizations and can lead to significant performance improvements. In Python lists, you would need to use loops or list comprehensions to achieve similar results, which are slower due to Python’s interpreted nature.'''
import numpy as np
import time

# Create large arrays
size = 10**6
array = np.arange(size)
py_list = list(range(size))

# Measure time for NumPy array addition
start = time.time()
np_result = array + 10
numpy_time = time.time() - start

# Measure time for Python list addition
start = time.time()
py_result = [x + 10 for x in py_list]
python_time = time.time() - start

print(f"NumPy Time: {numpy_time:.6f} seconds")
print(f"Python List Time: {python_time:.6f} seconds")
'''3. Performance with Large Data
Faster Execution: NumPy’s internal implementation is optimized for performance, utilizing highly efficient C and Fortran libraries. When performing mathematical operations on large datasets, NumPy can be significantly faster than Python lists. This is particularly true for operations that involve linear algebra, Fourier transforms, or statistical analysis.
4. Broadcasting
Efficiency in Operations: NumPy’s broadcasting feature allows for operations between arrays of different shapes without the need for explicitly creating larger arrays. This reduces memory usage and speeds up calculations.'''
# Example of broadcasting
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])
result = a + b  # b is broadcasted across rows of a
'''5. Advanced Indexing and Slicing
Convenience and Speed: NumPy offers powerful indexing and slicing capabilities, enabling efficient subsetting and manipulation of arrays. These operations are highly optimized and perform better than similar operations on Python lists, especially when dealing with large datasets.
6. Multithreading and Parallelization
Optimized Libraries: NumPy can take advantage of optimized libraries like BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package), which use multithreading and can execute operations in parallel. This leads to further speed improvements for operations on large arrays.
7. Performance on Mathematical Functions
Wide Range of Functions: NumPy provides a comprehensive suite of mathematical functions that operate directly on arrays. These functions are implemented in a way that maximizes performance and minimizes overhead compared to applying Python functions to lists, which requires iterating over elements.'''

#Example Benchmark Comparison
#To illustrate the performance difference, consider a benchmark comparing the time taken to compute the sum of a large array of numbers:
import numpy as np
import time

# Create a large NumPy array and Python list
size = 10**7
np_array = np.random.rand(size)
py_list = np_array.tolist()

# Timing NumPy sum
start = time.time()
np_sum = np.sum(np_array)
numpy_time = time.time() - start

# Timing Python list sum
start = time.time()
py_sum = sum(py_list)
python_time = time.time() - start

print(f"NumPy sum time: {numpy_time:.6f} seconds")
print(f"Python list sum time: {python_time:.6f} seconds")
'''Summary of Performance Benefits
Memory Efficiency: Lower memory consumption due to contiguous storage and fixed types.
Speed: Faster computations through vectorization, optimized algorithms, and reduced overhead.
Advanced Features: Broadcasting, efficient indexing, and comprehensive mathematical functions enhance both performance and ease of use.
Scalability: Better performance with large-scale numerical data, making NumPy the preferred choice for data-intensive applications like data analysis, scientific computing, and machine learning.
Overall, the design of NumPy is tailored for numerical computations, making it significantly more efficient than standard Python lists for large-scale numerical operations'''

In [ ]:
#7.Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
'''In NumPy, the vstack() and hstack() functions are used to stack arrays vertically and horizontally, respectively. Here’s a comparison of the two functions, along with examples demonstrating their usage.

1. vstack()
Purpose: Stacks arrays vertically (row-wise).
Input: Takes a tuple or a list of arrays and stacks them along the vertical axis (rows).'''
#Example of vstack()
import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack them vertically
vertical_stack = np.vstack((array1, array2))

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("\nVertical Stack:\n", vertical_stack)
#Output for vstack():
'''Array 1:
 [1 2 3]
Array 2:
 [4 5 6]'''

'''Vertical Stack:
 [[1 2 3]
 [4 5 6]]'''
 #2. hstack()
#Purpose: Stacks arrays horizontally (column-wise).
#Input: Takes a tuple or a list of arrays and stacks them along the horizontal axis (columns)
#Example of hstack()
import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack them horizontally
horizontal_stack = np.hstack((array1, array2))

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("\nHorizontal Stack:\n", horizontal_stack)
#Output for hstack():
'''Array 1:
 [1 2 3]
Array 2:
 [4 5 6]

Horizontal Stack:
 [1 2 3 4 5 6]'''
 #Comparison Summary
#vstack():

'''Takes two (or more) arrays and stacks them vertically (along rows).
The resulting array has an additional dimension compared to the input arrays.'''

#hstack():

'''Takes two (or more) arrays and stacks them horizontally (along columns).
The resulting array remains one-dimensional if the input arrays are one-dimensional.'''
#Use Cases
#vstack() is useful when you want to create a new array that combines multiple arrays into rows, such as when preparing data for matrix operations or creating datasets.
#hstack() is handy when you want to concatenate arrays side by side, often used when merging features or datasets.
#Both functions are straightforward to use and provide an efficient way to combine arrays in NumPy, enhancing flexibility in data manipulation.

In [ ]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
'''In NumPy, the fliplr() and flipud() methods are used to reverse the order of elements in arrays, but they operate along different axes. Here’s a detailed explanation of the differences between the two methods, along with their effects on various array dimensions.'''
#1. fliplr()
#Purpose: Flips (reverses) the array left to right.
#Effect on Dimensions:
'''2D Arrays: Reverses the order of columns in each row.
1D Arrays: It effectively reverses the entire array.'''
#Example of fliplr()
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Flip left to right
flipped_lr = np.fliplr(array_2d)

print("Original Array (2D):\n", array_2d)
print("\nFlipped Left to Right:\n", flipped_lr)
#Output for fliplr():
'''Original Array (2D):
 [[1 2 3]
 [4 5 6]]

Flipped Left to Right:
 [[3 2 1]
 [6 5 4]]'''

#2. flipud()
#Purpose: Flips (reverses) the array up to down.
#Effect on Dimensions:
'''2D Arrays: Reverses the order of rows in the array.
  1D Arrays: It effectively reverses the entire array.'''
  #Example of flipud()
  # Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Flip up to down
flipped_ud = np.flipud(array_2d)

print("Original Array (2D):\n", array_2d)
print("\nFlipped Up to Down:\n", flipped_ud)
#Output for flipud():
'''Original Array (2D):
 [[1 2 3]
 [4 5 6]]

Flipped Up to Down:
 [[4 5 6]
 [1 2 3]]'''
 #Comparison Summary
 #Direction of Flip:
''' fliplr() flips the array left to right (columns).
flipud() flips the array up to down (rows).'''
#Effect on 1D Arrays:
#Both fliplr() and flipud() behave similarly when applied to 1D arrays, reversing the order of elements.
#Example
arr_1d = np.array([1, 2, 3, 4])
#print(np.fliplr(arr_1d))  # Output: [4 3 2 1]
print(np.flipud(arr_1d))  # Output: [4 3 2 1]

#Effect on 2D Arrays:
#fliplr() reverses columns for each row.
#flipud() reverses rows for each column.
#Use Cases
#fliplr(): Useful when you need to change the orientation of the data horizontally, such as in image processing where flipping an image left to right is required.
#flipud(): Useful for vertically flipping data, which can be applicable in various applications such as reflecting data representations or images.
#Both functions are useful for manipulating the arrangement of data in arrays, and they provide an efficient way to modify array dimensions in NumPy.

In [ ]:
#9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
'''The array_split() method in NumPy is a versatile function that allows you to split an array into multiple sub-arrays. It can be particularly useful when you need to divide a dataset into smaller parts for analysis, processing, or validation.

Functionality of array_split()
Basic Usage:

The method can be used to split an array along a specified axis into a specified number of equal or nearly equal sub-arrays.'''
#It is defined as follows: numpy.array_split(ary, indices_or_sections, axis=0)
#Where:
#ary: The input array you want to split.
#indices_or_sections: Can be an integer (number of splits) or a sequence of indices (the exact points at which to split).
#axis: The axis along which to split the array (default is 0).
#Handling Uneven Splits:
#When the size of the array is not perfectly divisible by the number of splits specified, array_split() will handle this by distributing the remaining elements as evenly as possible among the resulting sub-arrays.
#This means that some sub-arrays may contain one more element than others.
#Example of array_split()
#Here’s an example that demonstrates how to use array_split() and how it handles uneven splits:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split the array into 3 equal parts
split_3 = np.array_split(array_1d, 3)

print("Original Array:\n", array_1d)
print("\nSplit into 3 Parts:\n", split_3)

# Split the array into 4 parts
split_4 = np.array_split(array_1d, 4)

print("\nSplit into 4 Parts:\n", split_4)
#Output:
'''Original Array:
 [1 2 3 4 5 6 7 8 9]

Split into 3 Parts:
 [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

Split into 4 Parts:
 [array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]'''

 #Key Points from the Example:
#When splitting the array into 3 parts, the elements are evenly distributed (3 elements in each of the first two parts, and 3 elements in the last part).
#When splitting into 4 parts, the first part gets 3 elements, while the remaining parts get 2 elements each. The function distributes the remaining elements as evenly as possible.
#Use Cases
#Data Preprocessing: Useful in machine learning for dividing data into training, validation, and test sets.
#Batch Processing: Splitting large datasets into manageable chunks for processing or analysis.
#Parallel Processing: Dividing work among different processors or threads by splitting data.
#Conclusion
#The array_split() method in NumPy is a powerful and flexible way to split arrays into smaller segments. Its ability to handle uneven splits gracefully makes it particularly useful for a variety of applications where data needs to be divided into smaller subsets. Whether you need equal splits or just want to divide an array into a specified number of parts, array_split() provides a simple and efficient solution.



In [ ]:
#10.Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
#Vectorization and broadcasting are two key concepts in NumPy that significantly enhance the efficiency and performance of array operations. Here’s a detailed explanation of each concept and how they contribute to efficient numerical computing.
#1. Vectorization
#Definition:

#Vectorization refers to the practice of replacing explicit loops in code with array expressions that operate on entire arrays. This allows for operations to be applied to all elements of an array simultaneously.

#How it Works:

#NumPy leverages low-level optimizations (written in C) to perform operations on arrays without the overhead of Python's interpreted loops. When you use NumPy functions, they are applied to entire arrays rather than individual elements, which leads to faster execution.

#Benefits:
#Performance: Vectorized operations are generally much faster than using loops in Python because they are executed in optimized compiled code rather than interpreted Python code.
#Conciseness: Vectorized code is often more concise and easier to read than its loop-based counterparts, making it more maintainable.
#Example of Vectorization:
import numpy as np

# Create a large array
array = np.arange(1000000)

# Vectorized operation: add 10 to each element
vectorized_result = array + 10
#In this example, the addition is applied to the entire array at once, resulting in faster execution compared to a loop.

#2. Broadcasting
#Definition:

#Broadcasting is a powerful mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes. It automatically expands the smaller array's dimensions to match the larger array's dimensions during operations.
#How it Works:

#When performing operations between arrays, NumPy compares their shapes:
#If the arrays have the same shape, they are compatible.
#If one of the arrays has a shape of 1 in any dimension, it can be broadcasted to match the other array's shape.
#Broadcasting can also occur across dimensions, allowing for flexible operations without needing to explicitly reshape arrays.

#Benefits:
#Flexibility: Broadcasting enables operations between arrays of different shapes, simplifying code and reducing the need for manual reshaping.
#Efficiency: It avoids unnecessary duplication of data, as the smaller array is not actually copied but rather virtually expanded to match the shape of the larger array.
#Example of Broadcasting:
import numpy as np

# Create a 1D array and a 2D array
array_1d = np.array([1, 2, 3])
array_2d = np.array([[10, 20, 30], [40, 50, 60]])

# Broadcasting: add 1D array to each row of the 2D array
result = array_2d + array_1d

print("Array 1D:\n", array_1d)
print("Array 2D:\n", array_2d)
print("\nResult after Broadcasting:\n", result)
#Output:
'''Array 1D:
 [1 2 3]
 Array 2D:

 [[10 20 30]
 [40 50 60]]

#Result after Broadcasting:
[[11 22 33]
 [41 52 63]]'''
 #In this example:

#The 1D array [1, 2, 3] is broadcasted to match the shape of the 2D array, allowing for element-wise addition without needing to manually expand the dimensions.
#Conclusion
#Contributions to Efficient Array Operations:
#Vectorization eliminates the need for slow Python loops, enabling operations to be executed at C-speed, thus significantly improving performance.
#Broadcasting allows for flexible and efficient arithmetic operations between arrays of different shapes, making it easier to write cleaner code without explicit reshaping or replication of data.
#Together, vectorization and broadcasting are foundational features of NumPy that empower users to write fast, efficient, and concise code for numerical computations, which is especially important when dealing with large datasets and complex mathematical operations in scientific computing, data analysis, and machine learning.


In [51]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
#We can create a 3x3 NumPy array with random integers between 1 and 100 using np.random.randint(), and then interchange its rows and columns (also known as transposing the array) using the .T attribute or the np.transpose() function. Here’s how to do it:

#Step-by-Step Code
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Print the original array
print("Original Array:\n", array_3x3)

# Interchange rows and columns (transpose the array)
transposed_array = array_3x3.T

# Print the transposed array
print("\nTransposed Array:\n", transposed_array)
#Example Output
#When you run the code, it might produce an output like this (the numbers will vary due to randomness):
'''Original Array:
 [[67 81  7]
 [15 60 42]
 [36 98 36]]

Transposed Array:
 [[67 15 36]
 [81 60 98]
 [ 7 42 36]]'''
# Explanation
#Creating the Array: The np.random.randint(1, 101, size=(3, 3)) function generates a 3x3 array with random integers in the range [1, 100].
#Transposing: The .T attribute transposes the array, interchanging its rows and columns. Alternatively, you can use np.transpose(array_3x3) to achieve the same result.
#This method effectively allows you to manipulate the structure of the array for various applications in data analysis, scientific computing, or any situation where you need to rearrange the data layout.


Original Array:
 [[13 31 25]
 [95 47 64]
 [32 32 61]]

Transposed Array:
 [[13 95 32]
 [31 47 32]
 [25 64 61]]


'Original Array:\n [[67 81  7]\n [15 60 42]\n [36 98 36]]\n\nTransposed Array:\n [[67 15 36]\n [81 60 98]\n [ 7 42 36]]'

In [52]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

#We can create a 1D NumPy array with 10 elements, and then reshape it into both a 2x5 array and a 5x2 array using the reshape() method. Here’s how to do it:

#Step-by-Step Code
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # Creates an array with elements from 0 to 9

# Print the original 1D array
print("Original 1D Array:\n", array_1d)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Print the 2x5 array
print("\nReshaped to 2x5 Array:\n", array_2x5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Print the 5x2 array
print("\nReshaped to 5x2 Array:\n", array_5x2)
#Example Output
#When we run the code, it might produce output like this:
'''Original 1D Array:
 [0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]'''
 #Explanation
#Generating the 1D Array: The np.arange(10) function creates a 1D array with 10 elements (from 0 to 9).
#Reshaping:
#The reshape(2, 5) method reshapes the array into a 2x5 format, organizing the elements into 2 rows and 5 columns.
#The reshape(5, 2) method reshapes the same array into a 5x2 format, resulting in 5 rows and 2 columns.
#Important Note
#The total number of elements must remain the same during reshaping. In this case, 10 elements can be arranged as either 2x5 or 5x2 arrays, ensuring the reshaping is valid.


Original 1D Array:
 [0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


'Original 1D Array:\n [0 1 2 3 4 5 6 7 8 9]\n\nReshaped to 2x5 Array:\n [[0 1 2 3 4]\n [5 6 7 8 9]]\n\nReshaped to 5x2 Array:\n [[0 1]\n [2 3]\n [4 5]\n [6 7]\n [8 9]]'

In [ ]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
#You can create a 4x4 NumPy array with random float values using np.random.rand(), and then add a border of zeros around it using np.pad(). Here’s how to do this step-by-step:

#Step-by-Step Code
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Print the original 4x4 array
print("Original 4x4 Array:\n", array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the resulting 6x6 array
print("\n6x6 Array with Border of Zeros:\n", array_with_border)
#Example Output
#When we run the code, it might produce output like this (the values will vary due to randomness):
'''Original 4x4 Array:
 [[0.85634757 0.64196935 0.53218686 0.62324912]
 [0.98218964 0.86907795 0.2059385  0.58616802]
 [0.29925891 0.94284874 0.51185149 0.87494276]
 [0.68191843 0.98107771 0.73682796 0.19431782]]

6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.85634757 0.64196935 0.53218686 0.62324912 0.        ]
 [0.         0.98218964 0.86907795 0.2059385  0.58616802 0.        ]
 [0.         0.29925891 0.94284874 0.51185149 0.87494276 0.        ]
 [0.         0.68191843 0.98107771 0.73682796 0.19431782 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]'''
 #Explanation
#Creating the Original Array: The np.random.rand(4, 4) function generates a 4x4 array filled with random float values between 0 and 1.
#Adding a Border:
#The np.pad() function is used to add a border of zeros around the original array.
#The pad_width=1 argument specifies that a border of 1 element should be added on all sides of the array.
#The mode='constant' argument indicates that the padding should be filled with constant values (in this case, zeros specified by constant_values=0).
#As a result, the original 4x4 array becomes a 6x6 array with zeros surrounding it.

In [15]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

#We can create an array of integers from 10 to 60 with a step of 5 using NumPy's np.arange() function. Here's how you can do it:

import numpy as np

# Creating the array
arr = np.arange(10, 61, 5)
print(arr)
#Output:[10 15 20 25 30 35 40 45 50 55 60]
#Explanation:
#np.arange(10, 61, 5) generates values starting from 10 up to (but including) 61, with a step of 5. Since the stop value is 61, the array includes 60 as the final value.



[10 15 20 25 30 35 40 45 50 55 60]


In [17]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.

#We can use NumPy's char module, which provides vectorized string operations, to apply case transformations like uppercase, lowercase, and title case to each element of a NumPy array of strings.

#Here's an example of how to do it:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_arr = np.char.upper(arr)      # Convert to uppercase
lowercase_arr = np.char.lower(arr)      # Convert to lowercase
titlecase_arr = np.char.title(arr)      # Convert to title case (capitalize each word)

print("Original Array:", arr)
print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Title Case:", titlecase_arr)

#Output:
#Original Array: ['python' 'numpy' 'pandas']
#Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
#Lowercase: ['python' 'numpy' 'pandas']
#Title Case: ['Python' 'Numpy' 'Pandas']

#Explanation:
#np.char.upper() converts all characters to uppercase.
#np.char.lower() converts all characters to lowercase.
#np.char.title() converts the first letter of each word to uppercase, leaving the rest in lowercase.

#These operations are applied element-wise to the entire array of strings.


Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


In [18]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
#To insert a space between each character of every word in a NumPy array of strings, you can use NumPy's char.join() function. This function allows you to insert a specified string (in this case, a space " ") between each character of the words in the array.

#Here’s how to do it:

import numpy as np

# Create a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character
spaced_words = np.char.join(' ', words)

print(spaced_words)
#Output:['p y t h o n' 'n u m p y' 'p a n d a s']
#Explanation:
#np.char.join(' ', words) inserts a space between every character in each word of the NumPy array.
#The ' ' specifies that a space is used as the separator between characters.
#This is applied element-wise to all words in the array.


['p y t h o n' 'n u m p y' 'p a n d a s']


In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division
#We can easily perform element-wise operations like addition, subtraction, multiplication, and division on two 2D NumPy arrays.
#Here's an example demonstrating these operations:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise division
division = array1 / array2

print("Array 1:\n", array1)
print("Array 2:\n", array2)

print("\nElement-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)

#Output
'''Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]'''

 #Explanation:
'''Addition (array1 + array2): Adds corresponding elements from both arrays.
Subtraction (array1 - array2): Subtracts corresponding elements of array2 from array1.
Multiplication (array1 * array2): Multiplies corresponding elements of the two arrays.
Division (array1 / array2): Divides corresponding elements of array1 by array2. Note that this results in floating-point numbers.'''


In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

'''To create a 5x5 identity matrix and then extract its diagonal elements using NumPy, follow these steps:

Use np.eye() to create an identity matrix.
Use np.diagonal() to extract the diagonal elements.'''

#Here’s the code:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("5x5 Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:", diagonal_elements)

#Output:

'''5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

Diagonal Elements: [1. 1. 1. 1. 1.]'''


'''Explanation:
np.eye(5) creates a 5x5 identity matrix where the diagonal elements are 1, and all other elements are 0.
np.diagonal(identity_matrix) extracts the diagonal elements, which in the case of an identity matrix are all 1's.'''


In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array
'''
To generate a NumPy array of 100 random integers between 0 and 1000 and find the prime numbers, we need to:

Use np.random.randint() to generate the random integers.
Define a helper function to check whether a number is prime.
Apply this function to the array to extract and display the prime numbers.'''

#Here’s the code to accomplish that:

import numpy as np

# Step 1: Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, 100)

# Step 2: Define a function to check for prime numbers
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Step 3: Apply the is_prime function to the array and find all primes
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

print("Random Integers Array:\n", random_integers)
print("\nPrime Numbers in the Array:\n", prime_numbers)

'''Explanation:
np.random.randint(0, 1000, 100) generates 100 random integers between 0 and 1000.
is_prime() is a helper function that checks if a number is prime. It returns False if the number is less than 2 or divisible by any number between 2 and the square root of the number. Otherwise, it returns True.
We use list comprehension to apply the is_prime() function to each element of the array and filter out the prime numbers.
The prime numbers are stored in prime_numbers and printed.'''

#Example Output:

'''Random Integers Array:
 [418 571 943 582 787 274 892 896 762 ... ]

Prime Numbers in the Array:
 [571 787 229 151 809 ... ]'''
 #(Note: The actual prime numbers will vary since the random integers will change each time we run the code.)

In [28]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
'''To represent daily temperatures for a month (let’s assume 30 days) in a NumPy array and calculate the weekly averages, you can follow these steps:

Create a NumPy array of 30 random temperatures (for example, ranging between 15°C and 35°C).
Reshape the array into 4 weeks (since a month typically has about 4 weeks).
Calculate the weekly averages using np.mean().'''
#Here’s the code:

import numpy as np

# Step 1: Create a NumPy array representing daily temperatures for 30 days
daily_temperatures = np.random.randint(15, 36, 30)

# Step 2: Reshape the array into 4 weeks (4 weeks * 7 days) weekly_temperatures = daily_temperatures.reshape(4, 7)

# Step 3: Calculate the weekly averagesweekly_averages = np.mean(weekly_temperatures, axis=1)

#print("Daily Temperatures:\n", daily_temperatures)
#print("\nWeekly Temperatures:\n", weekly_temperatures)
#print("\nWeekly Averages:\n", weekly_averages)


'''Explanation:
np.random.randint(15, 36, 30) generates 30 random integers between 15°C and 35°C to represent daily temperatures.
reshape(4, 7) reshapes the 1D array into a 2D array with 4 rows (weeks) and 7 columns (days per week).
np.mean(weekly_temperatures, axis=1) calculates the mean temperature for each week. The axis=1 parameter specifies that the mean is computed across the columns (i.e., for each week).'''
#Example Output:
'''Daily Temperatures:
 [26 34 33 23 35 31 24 21 21 20 22 33 20 29 29 21 26 34 34 29 31 32 15 33 29 19 17 32 34 28]

Weekly Temperatures:
 [[26 34 33 23 35 31 24]
 [21 21 20 22 33 20 29]
 [29 21 26 34 34 29 31]
 [32 15 33 29 19 17 32]]

Weekly Averages:
 [29.42857143 23.71428571 29.14285714 25.28571429]'''

 #Interpretation:
#The daily temperatures array contains temperatures for each of the 30 days.
#The weekly averages show the mean temperature for each week (rounded to 8 decimal places).

'Daily Temperatures:\n [26 34 33 23 35 31 24 21 21 20 22 33 20 29 29 21 26 34 34 29 31 32 15 33 29 19 17 32 34 28]\n\nWeekly Temperatures:\n [[26 34 33 23 35 31 24]\n [21 21 20 22 33 20 29]\n [29 21 26 34 34 29 31]\n [32 15 33 29 19 17 32]]\n\nWeekly Averages:\n [29.42857143 23.71428571 29.14285714 25.28571429]'